### ISSUE TITLE
HTCondorSubmitter tries to access the first element of a potentially empty list

### ISSUE THREAD

**Issue by benkrikler** [alphatwirl/alphatwirl#37]
[Line 74 of HTCondorJobSubmitter](https://github.com/alphatwirl/alphatwirl/blob/master/alphatwirl/concurrently/HTCondorJobSubmitter.py#L74) calls a function then immediately gets the first element in what it returns.  However two of the three return statements in that function return empty lists, and so this can lead to the code crashing.

**Comment by TaiSakuma** [comment]
i can find only two return statemnts in the function. where do you three?

**Comment by benkrikler** [comment]
Sorry, I meant one of the two.

**Comment by TaiSakuma** [comment]
i see. when `run_multiple()` is called from `run()`, it never returns with the first return staement and it always returns a list of one element with the second return stament.

**Comment by benkrikler** [comment]
I posted this cause I saw it die, but since my version of AlphaTwirl is older than the current one, and things look like they've changed It's possible this has been addressed.  

Although if I look at the code, the way that function is used, it does seem to be expected to return a single item, and not a list (given that you just take the first item in the list regardless of what the function returns).  So it seems safer to me to just make the function return a single item or None instead of a list of things...

**Comment by TaiSakuma** [comment]
the function generally returns a list of as many items as `package_indices`. it returns a list of a single item when called by `run()` because `run()` gives one package index to the function. 

the function is primarily called by `TaskPackageDropbox` with multiple package indices. 

`run()` is the older version of `run_multiple()`. `run()` is still there for backwardcompatiblity.
